apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: wordpress-cluster
servers: 1
agents: 3
image: rancher/k3s:v1.28.5-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 3001:3001
    nodeFilters:
      - loadbalancer
  - port: 8025:8025
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "300s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"

