.PHONY: create-cluster delete-cluster build-images deploy undeploy status logs scale validate health backup restore complete-setup complete-teardown

create-cluster:
	cd scripts && ./create-cluster.sh

delete-cluster:
	cd scripts && ./delete-cluster.sh

build-images:
	cd scripts && ./build-images.sh

deploy:
	cd scripts && ./deploy.sh

undeploy:
	cd scripts && ./undeploy.sh

status:
	cd scripts && ./status.sh

logs:
	cd scripts && ./logs.sh

scale:
	cd scripts && ./scale.sh

validate:
	cd scripts && ./validate-manifests.sh

health:
	cd scripts && ./check-health.sh

backup:
	cd scripts && ./backup.sh

restore:
	cd scripts && ./restore.sh

complete-setup:
	cd scripts && ./complete-setup.sh

complete-teardown:
	cd scripts && ./complete-teardown.sh

